name: Android

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Node
      uses: actions/setup-node@v1
      with:
          node-version: 16

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'
          
    - name: Install node_modules
      run: |
        yarn install --frozen-lockfile

    - name: Gradle cache
      uses: gradle/gradle-build-action@v2
        
    - name: AVD cache
      uses: actions/cache@v3
      id: avd-cache
      with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
          api-level: 30
          target: google_apis
          arch: x86_64
          name: Pixel_3a_API_33_arm64-v8a
          script: npx detox test --configuration android.emu.release
 
        






